version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: attendance-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: attendance-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/attendance_db
      - JWT_SECRET=supersecretkey
      - PORT=5000
    depends_on:
      - mongo
volumes:
  mongo_data: 