version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: attendance-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: attendance-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb+srv://nuwanisitharacom:nuwani808@cluster0.njcwh4b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretkey
      - PORT=5000
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: attendance-frontend
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
volumes:
  mongo_data: 